//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Haven.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 660
        ///property float x
        ///property float y
        ///property float z
        ///element face 220
        ///property list uchar int vertex_indices
        ///end_header
        ///-390.000000 882.644958 -500.000000
        ///-390.000000 900.000000 -496.000000
        ///-400.000000 889.999939 -490.000000
        ///-400.000000 889.999939 -490.000000
        ///-390.000000 900.000000 -496.000000
        ///-385.743500 895.775024 0.000000
        ///-400.000000 889.999939 -490.000000
        ///-385.743500 895.775024 0.000000
        ///-395.743500 885.775085 0.000000
        ///-400. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelCBOX {
            get {
                return ResourceManager.GetString("ModelCBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 36
        ///property float x
        ///property float y
        ///property float z
        ///element face 12
        ///property list uchar int vertex_indices
        ///end_header
        ///400.000000 -400.000000 -400.000000
        ///400.000000 400.000000 -400.000000
        ///-400.000000 -400.000000 -400.000000
        ///-400.000000 -400.000000 -400.000000
        ///400.000000 400.000000 -400.000000
        ///-400.000000 400.000000 -400.000000
        ///-400.000000 -400.000000 400.000000
        ///400.000000 -400.000000 400.000000
        ///-400.000000 -400.000000 -400.000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelCube {
            get {
                return ResourceManager.GetString("ModelCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 7500
        ///property float x
        ///property float y
        ///property float z
        ///element face 2500
        ///property list uchar int vertex_indices
        ///end_header
        ///-823.943542 423.810486 -48.693802
        ///-838.230530 427.243408 -50.887699
        ///-823.201477 427.882294 -53.639400
        ///-838.230530 427.243408 -50.887699
        ///-823.943542 423.810486 -48.693802
        ///-833.036133 402.350220 -48.007401
        ///-823.201477 427.882294 -53.639400
        ///-838.230530 427.243408 -50.887699
        ///-820.979004 426.858429 -67.292305
        ///-82 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelDoll {
            get {
                return ResourceManager.GetString("ModelDoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 1662
        ///property float x
        ///property float y
        ///property float z
        ///element face 554
        ///property list uchar int vertex_indices
        ///end_header
        ///34.927898 0.000000 -63.933701
        ///14.538100 0.000000 -63.933701
        ///67.338699 0.000000 -1.737100
        ///67.338699 0.000000 -1.737100
        ///14.538100 0.000000 -63.933701
        ///20.293200 0.000000 33.710300
        ///67.338699 0.000000 -1.737100
        ///20.293200 0.000000 33.710300
        ///68.672600 0.000000 17.337599
        ///68.672600 0.000000 17.337599
        ///20.293200 0.0000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelGako {
            get {
                return ResourceManager.GetString("ModelGako", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 1698
        ///property float x
        ///property float y
        ///property float z
        ///element face 566
        ///property list uchar int vertex_indices
        ///end_header
        ///85.314102 105.866096 -18.663099
        ///86.589996 109.303406 -34.053200
        ///85.314102 102.802895 -36.594799
        ///86.589996 109.303406 -34.053200
        ///85.314102 105.866096 -18.663099
        ///71.835098 120.495293 -11.897800
        ///86.589996 109.303406 -34.053200
        ///71.835098 120.495293 -11.897800
        ///75.722298 119.466904 -24.523600
        ///85.314102 105.866096 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelKerotan {
            get {
                return ResourceManager.GetString("ModelKerotan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ply
        ///format ascii 1.0
        ///comment mesh2rdm output
        ///element vertex 1014
        ///property float x
        ///property float y
        ///property float z
        ///element face 338
        ///property list uchar int vertex_indices
        ///end_header
        ///675.000000 100.000000 2000.000000
        ///675.000000 100.000000 1879.999878
        ///1325.000000 100.000000 2000.000000
        ///1325.000000 100.000000 2000.000000
        ///675.000000 100.000000 1879.999878
        ///1325.000000 100.000000 1879.999878
        ///1325.000000 100.000000 -2000.000000
        ///1325.000000 100.000000 -1879.999878
        ///675.000000 100.000000 -2000.0000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelTerminal {
            get {
                return ResourceManager.GetString("ModelTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShaderFragment {
            get {
                object obj = ResourceManager.GetObject("ShaderFragment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShaderVert {
            get {
                object obj = ResourceManager.GetObject("ShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
